### ISSUE TITLE
希望加入语音领域NLP相关工作分类

### ISSUE THREAD

**Issue by Chaotic-chaos** [TingFree/NLPer-Arsenal#1]
### 感谢您们的工作！
- 项目结构真的好清晰
- NLPer感动的留下泪水

### 小建议
- 浏览下来发现并没有专门的语音领域分类
- 语音领域目前是NLP比较热门的一个研究点，希望作者能加入语音领域相关工作整理

### 感谢您阅读这条issue

**Comment by TingFree** [comment]
我们注意到了您提交的需求，之后会调查整理语音领域的资料，敬请关注
