### ISSUE TITLE
留意到example的text_classification.py以及center_controller.py里使用的trainer居然是不一致，请问是故意这样设计吗？应该使用哪一个？

### ISSUE THREAD

**Issue by JaxChan25** [TingFree/NLPer-Arsenal#12]
其中一个：
codes\nlper\mini_pytorch_lightning\trainer.py
另一个：
codes\nlper\modules\trainer.py

很不解为什么不用一直接口的，应该使用哪一个比较好？

**Comment by JaxChan25** [comment]
我感觉作者是因为方便展示，才写了codes\nlper\modules\trainer.py（一个简略版），其实用codes\nlper\mini_pytorch_lightning\trainer.py就很好了

**Comment by TingFree** [comment]
mini_pytorch_lightning中的trainer主要集成到框架里，考虑到对新手可能不是那么友好，所以另外实现了一个更简洁直观的trainer，用在example中。这两者功能基本一致，不过前者还没有实现加载模型继续训练的功能。
