### ISSUE TITLE
往期竞赛:  KDD Cup 2022, 文本相关性问题

### ISSUE THREAD

**Issue by cuixuage** [TingFree/NLPer-Arsenal#13]
RT
比赛链接:

> https://www.aicrowd.com/challenges/esci-challenge-for-improving-product-search

三个子任务: NDCG, Four-Classification, Binary-Classification

比赛讨论区:
https://www.aicrowd.com/challenges/esci-challenge-for-improving-product-search/discussion
论文主页(TBD):
https://amazonkddcup.github.io/

**Comment by cuixuage** [comment]
task2,task3  第二名方案，https://discourse.aicrowd.com/t/ets-lab-our-solution/7961
task2，task3 第一名方案，https://discourse.aicrowd.com/t/my-solution-good-good-study-day-day-up/7965
task1，第五名方案  https://discourse.aicrowd.com/t/solution-zhichunroad-5th-task1-7th-task2-and-8th-task3/8006

**Comment by TingFree** [comment]
非常感谢您对NLPer-Arsenal项目的支持，我们会在之后的更新中补充相关内容

**Comment by Lxiaoxue** [comment]
我对这个医疗事件抽取非常感兴趣，有没有复现的源码，参考学习一下

**Comment by GuiminChen** [comment]
您好，您的来信已收到，我会尽快回复您的邮件。
============
祝您生活愉快！

**Comment by TingFree** [comment]
> 我对这个医疗事件抽取非常感兴趣，有没有复现的源码，参考学习一下

可以试试这个，文档级事件抽取的一些复现，[DocEE](https://github.com/Spico197/DocEE)

**Comment by Lxiaoxue** [comment]
好的，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TingFree/NLPer-Arsenal] 往期竞赛:  KDD Cup 2022, 文本相关性问题 (Issue #13)





  
我对这个医疗事件抽取非常感兴趣，有没有复现的源码，参考学习一下
  
可以试试这个，文档级事件抽取的一些复现，DocEE

**Comment by TingFree** [comment]
> task2,task3 第二名方案，https://discourse.aicrowd.com/t/ets-lab-our-solution/7961 task2，task3 第一名方案，https://discourse.aicrowd.com/t/my-solution-good-good-study-day-day-up/7965 task1，第五名方案 https://discourse.aicrowd.com/t/solution-zhichunroad-5th-task1-7th-task2-and-8th-task3/8006
> 
> 其他方案，等待论文放出后，可以对照这个帖子查看。 https://discourse.aicrowd.com/t/final-winners-announcement/7974

已更新2022 Amazon KDD Cup竞赛方案 -> https://github.com/TingFree/NLPer-Arsenal/blob/master/%E5%BE%80%E6%9C%9F%E7%AB%9E%E8%B5%9B/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB/2022%20Amazon%20KDD%20Cup%20(task2%20Multi-class%20Product%20Classification%2C%20task3%20Product%20Substitute%20Identification).md
