### ISSUE TITLE
2021.09已经停止更新了吗？

### ISSUE THREAD

**Issue by cuixuage** [TingFree/NLPer-Arsenal#4]
RT
好兄弟，帮忙看一下啊

**Comment by TingFree** [comment]
@cuixuage 
不是的，只是出于人手与进度上的考虑，notion页面暂不更新（虽然也没怎么更新过），github正常更新，具体安排可以看Project中的Schedule（明年的计划还没出，但大概率会继续更新）。此外，感谢您对本项目的关注。
