### ISSUE TITLE
同样的想法

### ISSUE THREAD

**Issue by SWHL** [TingFree/NLPer-Arsenal#6]
-  今天看到你们这个项目，发现和我想的一样🤜🤛
- 我收集整理的是CVer相关的赛事分享贴 [AI-Competition-Collections](https://github.com/SWHL/AI-Competition-Collections)
- 最近也正想着收集其他领域的赛事分享贴子呢，偶然看到你们的项目，发现你们的NLPer-Arsenal-Notion和我正在做的想法一样
- 想问一下，平时搜集相关资料都有什么渠道？

**Comment by TingFree** [comment]
@SWHL NLP领域的话，主要收录会议评测和零散竞赛，会议包括CCL/CCKS/SMP/NLPCC，这些评测任务多半可以在会议官网找到，或者阿里天池/aistudio/biendata，其它竞赛也可以在上面找到，竞赛结束后，多去竞赛官网讨论区/知乎上看看有没有选手分享方案；另外还有NAACL/COLING/EMNLP/AAAI/ACL等顶会，这上面也有很多workshop可以跟踪，要多去会议官网看看，有些可以在codalab上找到。一般来说，和会议相关的评测任务总是能有一些评测论文放出来，这也是关注的重点。我对CV不太了解，不过应该是差不多的。共勉

**Comment by SWHL** [comment]
感谢感谢
