### ISSUE TITLE
建议赛事表格加一列“赛事状态”

### ISSUE THREAD

**Issue by cn-Wziv** [TingFree/NLPer-Arsenal#7]
感谢你们的努力
如题，希望增加一列赛事状态，“进行中”，“已结束”
能够极大提高使用体验

**Comment by TingFree** [comment]
@cn-Wziv 感谢您对本项目的认可，事实上，这个可以根据报名时间来判断，同时我们通过结束时间作为赛事的终止时间（通常是决赛答辩/workshop/颁奖）
