### ISSUE TITLE
CHIP2021任务三第三名和任务一第一名代码已开源

### ISSUE THREAD

**Issue by xiangking** [TingFree/NLPer-Arsenal#8]
CHIP2021-Task3-临床术语标准化任务-第三名：https://github.com/DataArk/CHIP2021-Task3-Top3
CHIP2021-Task1-医学对话临床发现阴阳性判别任务-第一名：https://github.com/DataArk/CHIP2021-Task1-Top1

**Comment by TingFree** [comment]
感谢您对本项目的贡献，我们将在下次更新中添加相关内容
